name: Lint and Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: yarn
    - name: Install Dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
